# Generated by Django 4.2.16 on 2024-12-05 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorieTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='protein_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='SearchedFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
