# Generated by Django 4.2.16 on 2024-12-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0002_fooditem_protein_per_gram_searchedfooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieintakeentry',
            name='calculated_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
