# Generated by Django 4.2.16 on 2024-12-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0004_fooditem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCalculatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('biological_sex', models.CharField(max_length=10)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(max_length=20)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calorie_target', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
