# Generated by Django 5.0.3 on 2024-09-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_phone_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_to_text',
            field=models.BooleanField(default=False),
        ),
    ]
