# Generated by Django 4.2.16 on 2024-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_consent_to_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
