# Generated by Django 4.2.16 on 2024-11-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
