# Generated by Django 4.2.16 on 2024-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_donor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='message',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
