# Generated by Django 4.2.16 on 2024-12-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_donor_message_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
    ]
